include: package:flutter_lints/flutter.yaml

analyzer:
    exclude:
    - "**/generated/**"
    - "**.g.dart"
    - "**/di.*.dart"

linter:
  rules:
    - prefer_relative_imports
    - unnecessary_breaks
